[doc]
name = 'tex'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'thesis'
type = 'pdf'
index = 'thesis-main.tex' 
preamble = ''
postamble = ''
shell_escape = true